// This file will be auto-generated by running:
// npx supabase gen types typescript --local > lib/types/database.ts
//
// For now, use the manual types in leads.ts and users.ts.
// After setting up Supabase local dev, regenerate this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
